### ISSUE TITLE
Feature Request: Autoconfig for ActionCable Redis adaptor

### ISSUE THREAD

**Issue by squeedee** [paketo-community/ruby#12]
# If you were attempting to accomplish a task, what was it you were attempting to do?

I wanted to push my Rails 6 app, with ActionCable, where ActionCable is configured with the :redis adaptor. This is the default for production rails 6 ActionCable apps 

The config in 'config/cable.yml':
```
development:
  adapter: async
test:
  adapter: test
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: my_app_production
```

# What did you expect to happen?

I expected the buildpack to look for the first VCAP_SERVICES entry tagged as "redis" and use it's `credentials` to rewrite `config/cable`. 

I only expect this if `config/cable.yml` matches `production: { adapter: redis}`

# What was the actual behavior?

`config/cable.yml` was untouched, and I needed to add my own VCAP_SERVICES parser to the app so as to keep my app deployments simple.

# Can you provide a sample app?
I could if pressed. 

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction
